/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2019-10-17 02:50:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>content</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        <div class=\"inner-block\">\n");
      out.write("            <!--market updates updates-->\n");
      out.write("            <div class=\"market-updates\">\n");
      out.write("                <div class=\"col-md-4 market-update-gd\">\n");
      out.write("                    <div class=\"market-update-block clr-block-1\">\n");
      out.write("                        <div class=\"col-md-8 market-update-left\">\n");
      out.write("                            <h3>83</h3>\n");
      out.write("                            <h4>Registered User</h4>\n");
      out.write("                            <p>Other hand, we denounce</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 market-update-right\">\n");
      out.write("                            <i class=\"fa fa-file-text-o\"> </i>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"clearfix\"> </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4 market-update-gd\">\n");
      out.write("                    <div class=\"market-update-block clr-block-2\">\n");
      out.write("                        <div class=\"col-md-8 market-update-left\">\n");
      out.write("                            <h3>135</h3>\n");
      out.write("                            <h4>Daily Visitors</h4>\n");
      out.write("                            <p>Other hand, we denounce</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 market-update-right\">\n");
      out.write("                            <i class=\"fa fa-eye\"> </i>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"clearfix\"> </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4 market-update-gd\">\n");
      out.write("                    <div class=\"market-update-block clr-block-3\">\n");
      out.write("                        <div class=\"col-md-8 market-update-left\">\n");
      out.write("                            <h3>23</h3>\n");
      out.write("                            <h4>New Messages</h4>\n");
      out.write("                            <p>Other hand, we denounce</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 market-update-right\">\n");
      out.write("                            <i class=\"fa fa-envelope-o\"> </i>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"clearfix\"> </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"clearfix\"> </div>\n");
      out.write("            </div>\n");
      out.write("            <!--market updates end here-->\n");
      out.write("            <!--mainpage chit-chating-->\n");
      out.write("            <div class=\"chit-chat-layer1\">\n");
      out.write("                <div class=\"col-md-6 chit-chat-layer1-left\">\n");
      out.write("                    <div class=\"work-progres\">\n");
      out.write("                        <div class=\"chit-chat-heading\">\n");
      out.write("                            Recent Followers\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"table-responsive\">\n");
      out.write("                            <table class=\"table table-hover\">\n");
      out.write("                                <thead>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>#</th>\n");
      out.write("                                        <th>Project</th>\n");
      out.write("                                        <th>Manager</th>                                   \n");
      out.write("\n");
      out.write("                                        <th>Status</th>\n");
      out.write("                                        <th>Progress</th>\n");
      out.write("                                    </tr>\n");
      out.write("                                </thead>\n");
      out.write("                                <tbody>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>1</td>\n");
      out.write("                                        <td>Face book</td>\n");
      out.write("                                        <td>Malorum</td>                                 \n");
      out.write("\n");
      out.write("                                        <td><span class=\"label label-danger\">in progress</span></td>\n");
      out.write("                                        <td><span class=\"badge badge-info\">50%</span></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>2</td>\n");
      out.write("                                        <td>Twitter</td>\n");
      out.write("                                        <td>Evan</td>                               \n");
      out.write("\n");
      out.write("                                        <td><span class=\"label label-success\">completed</span></td>\n");
      out.write("                                        <td><span class=\"badge badge-success\">100%</span></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>3</td>\n");
      out.write("                                        <td>Google</td>\n");
      out.write("                                        <td>John</td>                                \n");
      out.write("\n");
      out.write("                                        <td><span class=\"label label-warning\">in progress</span></td>\n");
      out.write("                                        <td><span class=\"badge badge-warning\">75%</span></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>4</td>\n");
      out.write("                                        <td>LinkedIn</td>\n");
      out.write("                                        <td>Danial</td>                                 \n");
      out.write("\n");
      out.write("                                        <td><span class=\"label label-info\">in progress</span></td>\n");
      out.write("                                        <td><span class=\"badge badge-info\">65%</span></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>5</td>\n");
      out.write("                                        <td>Tumblr</td>\n");
      out.write("                                        <td>David</td>                                \n");
      out.write("\n");
      out.write("                                        <td><span class=\"label label-warning\">in progress</span></td>\n");
      out.write("                                        <td><span class=\"badge badge-danger\">95%</span></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>6</td>\n");
      out.write("                                        <td>Tesla</td>\n");
      out.write("                                        <td>Mickey</td>                                  \n");
      out.write("\n");
      out.write("                                        <td><span class=\"label label-info\">in progress</span></td>\n");
      out.write("                                        <td><span class=\"badge badge-success\">95%</span></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6 chit-chat-layer1-rit\">    \t\n");
      out.write("                    <div class=\"geo-chart\">\n");
      out.write("                        <section id=\"charts1\" class=\"charts\">\n");
      out.write("                            <div class=\"wrapper-flex\">\n");
      out.write("\n");
      out.write("                                <table id=\"myTable\" class=\"geoChart tableChart data-table col-table\" style=\"display:none;\">\n");
      out.write("                                    <caption>Student Nationalities Table</caption>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th scope=\"col\" data-type=\"string\">Country</th>\n");
      out.write("                                        <th scope=\"col\" data-type=\"number\">Number of Students</th>\n");
      out.write("                                        <th scope=\"col\" data-role=\"annotation\">Annotation</th>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>China</td>\n");
      out.write("                                        <td align=\"right\">20</td>\n");
      out.write("                                        <td align=\"right\">20</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>Colombia</td>\n");
      out.write("                                        <td align=\"right\">5</td>\n");
      out.write("                                        <td align=\"right\">5</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>France</td>\n");
      out.write("                                        <td align=\"right\">3</td>\n");
      out.write("                                        <td align=\"right\">3</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>Italy</td>\n");
      out.write("                                        <td align=\"right\">1</td>\n");
      out.write("                                        <td align=\"right\">1</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>Japan</td>\n");
      out.write("                                        <td align=\"right\">18</td>\n");
      out.write("                                        <td align=\"right\">18</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>Kazakhstan</td>\n");
      out.write("                                        <td align=\"right\">1</td>\n");
      out.write("                                        <td align=\"right\">1</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>Mexico</td>\n");
      out.write("                                        <td align=\"right\">1</td>\n");
      out.write("                                        <td align=\"right\">1</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>Poland</td>\n");
      out.write("                                        <td align=\"right\">1</td>\n");
      out.write("                                        <td align=\"right\">1</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>Russia</td>\n");
      out.write("                                        <td align=\"right\">11</td>\n");
      out.write("                                        <td align=\"right\">11</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>Spain</td>\n");
      out.write("                                        <td align=\"right\">2</td>\n");
      out.write("                                        <td align=\"right\">2</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>Tanzania</td>\n");
      out.write("                                        <td align=\"right\">1</td>\n");
      out.write("                                        <td align=\"right\">1</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>Turkey</td>\n");
      out.write("                                        <td align=\"right\">2</td>\n");
      out.write("                                        <td align=\"right\">2</td>\n");
      out.write("                                    </tr>\n");
      out.write("\n");
      out.write("                                </table>\n");
      out.write("\n");
      out.write("                                <div class=\"col geo_main\">\n");
      out.write("                                    <h3 id=\"geoChartTitle\">World Market</h3>\n");
      out.write("                                    <div id=\"geoChart\" class=\"chart\"> </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            </div><!-- .wrapper-flex -->\n");
      out.write("                        </section>\t\t\t\t\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"clearfix\"> </div>\n");
      out.write("            </div>\n");
      out.write("            <!--main page chit chating end here-->\n");
      out.write("            <!--main page chart start here-->\n");
      out.write("            <div class=\"main-page-charts\">\n");
      out.write("                <div class=\"main-page-chart-layer1\">\n");
      out.write("                    <div class=\"col-md-6 chart-layer1-left\"> \n");
      out.write("                        <div class=\"glocy-chart\">\n");
      out.write("                            <div class=\"span-2c\">  \n");
      out.write("                                <h3 class=\"tlt\">Sales Analytics</h3>\n");
      out.write("                                <canvas id=\"bar\" height=\"300\" width=\"400\" style=\"width: 400px; height: 300px;\"></canvas>\n");
      out.write("                                <script>\n");
      out.write("                                    var barChartData = {\n");
      out.write("                                        labels: [\"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", \"Jun\", \"jul\"],\n");
      out.write("                                        datasets: [\n");
      out.write("                                            {\n");
      out.write("                                                fillColor: \"#FC8213\",\n");
      out.write("                                                data: [65, 59, 90, 81, 56, 55, 40]\n");
      out.write("                                            },\n");
      out.write("                                            {\n");
      out.write("                                                fillColor: \"#337AB7\",\n");
      out.write("                                                data: [28, 48, 40, 19, 96, 27, 100]\n");
      out.write("                                            }\n");
      out.write("                                        ]\n");
      out.write("\n");
      out.write("                                    };\n");
      out.write("                                    new Chart(document.getElementById(\"bar\").getContext(\"2d\")).Bar(barChartData);\n");
      out.write("\n");
      out.write("                                </script>\n");
      out.write("                            </div> \t\t\t  \t\t   \t\t\t\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6 chart-layer1-right\"> \n");
      out.write("                        <div class=\"user-marorm\">\n");
      out.write("                            <div class=\"malorum-top\">\t\t\t\t\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"malorm-bottom\">\n");
      out.write("                                <span class=\"malorum-pro\"> </span>\n");
      out.write("                                <h4>unde omnis iste</h4>\n");
      out.write("                                <h2>Melorum</h2>\n");
      out.write("                                <p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising.</p>\n");
      out.write("                                <ul class=\"malorum-icons\">\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-facebook\"> </i>\n");
      out.write("                                            <div class=\"tooltip\"><span>Facebook</span></div>\n");
      out.write("                                        </a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-twitter\"> </i>\n");
      out.write("                                            <div class=\"tooltip\"><span>Twitter</span></div>\n");
      out.write("                                        </a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-google-plus\"> </i>\n");
      out.write("                                            <div class=\"tooltip\"><span>Google</span></div>\n");
      out.write("                                        </a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"clearfix\"> </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
